### PR TITLE
WIP v0.7 - Pyclient

### PR DESCRIPTION
**Pull request by npiganeau**

### CODE REVIEW

**Comment by Sharpe49** [comment]
I don't know if you have already seen those bugs, but I found these in 0.7 version : 
- Track circuit simulation does not work properly
- Some block signals (=> with route) do not update when the next signal is opened

**Comment by npiganeau** [comment]
@Sharpe49 thanks for reporting. 

I've seen the pb about track circuit, but not the second one. Do you have an example ?

**Comment by npiganeau** [comment]
Ok I've found it

**Comment by Sharpe49** [comment]
Alright, with your patch, it has also fixed the updating of the block signal.
But sometimes, the block signal (or automatic signal) behind a train stays open. For example, in Gretz, take the first train from the yard to Tournan, then when it goes towards Paris, when the train is at Ozoir la Ferriere, the signal behind it is open. It doesn't care if the next items are occupied anymore.
2019-05-13 00_45_36-ts2 - Train Signalling Simulator - Gretz-Armainvilliers

Another problem : when a route signal is closed, most of the time, the train passes it and gets blocked.

**Comment by npiganeau** [comment]
@Sharpe49 I've made some corrections. Can you check again with the latest server in the devel branch ?

**Comment by npiganeau** [comment]
Not good yet. Still some work ongoing

**Comment by npiganeau** [comment]
Now it should be good with the server in the devel branch. I had trouble with opposite block signals which did not update as it should, but now this is fixed.

**Comment by Sharpe49** [comment]
It's already better : the SEMAPHORE_AUTO signals now work properly.
And the trains are still crossing the C aspect.

I am currently modifying the French signals library in order to add the blinking aspects.
I will then update the Gretz map.

**Comment by npiganeau** [comment]
Great! Can you tell me if trains still cross C signals if you have a smaller simulation speed (let's say 1x or 2x) ? I had issues about this at one time.

**Comment by npiganeau** [comment]
Found it: Yellow signals are not enforced properly, and it's too late when train see the red signal. I must fix that.

**Comment by Sharpe49** [comment]
That works great now.

Another bug : in the editor, in the route page, when you select the origin, then the destination of a route, the program crashes.

**Comment by npiganeau** [comment]
Fixed both

**Comment by npiganeau** [comment]
I have an issue with signals aspects with several actions (e.g. FR_BAL_S) which makes ts2 crash.

**Comment by Sharpe49** [comment]
Yes, I have some crashes too : 
panic: runtime error: index out of range

goroutine 419 [running]:
github.com/ts2/ts2-sim-server/simulation.(*Train).ApplicableAction(...)
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/trains.go:500
github.com/ts2/ts2-sim-server/simulation.(*Train).updateSignalActions(0xc0002d1a20)
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/trains.go:362 +0xb45
github.com/ts2/ts2-sim-server/simulation.(*Train).advance(0xc0002d1a20, 0x9502f900)
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/trains.go:198 +0x6e
github.com/ts2/ts2-sim-server/simulation.(*Simulation).updateTrains(0xc00005b800)
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/simulation.go:378 +0x116
github.com/ts2/ts2-sim-server/simulation.(*Simulation).run(0xc00005b800)
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/simulation.go:306 +0x76
created by github.com/ts2/ts2-sim-server/simulation.(*Simulation).Start
        C:/Users/gniew/Desktop/ts2-sim-server/simulation/simulation.go:288 +0x7a
WS Closed

Can you also check on the TRAIN_PRESENT conditions, please ?
It doesn't work on Gretz for the signals at the extremities of the map.

**Comment by npiganeau** [comment]
I think you have a wrong configuration for extremity signals. You should have something like the "UK_3_ASPECTS_TP" with only the "TRAIN_NOT_PRESENT_ON_ITEMS" condition, because an aspect will only show if ALL conditions are met. In your case, the next signal state condition is never met because there is no next signal, so it falls back to red all the time.

**Comment by npiganeau** [comment]
index out of range crash is fixed

I found a new data race crash I'll have to fix (concurrent map iteration and map write on trainEndsFW and trainEndsBK maps).

**Comment by Sharpe49** [comment]
Ok, next crash is much later in the simulation : 
INFO[05-25|03:59:27] Train TAVA118401 entered the area on time module=simulation msgType=2
Traceback (most recent call last):
  File "C:\Users\gniew\Desktop\ts2\ts2\mainwindow.py", line 948, in executeCallback
    hData[1](hData[0], msgData["object"])
  File "C:\Users\gniew\Desktop\ts2\ts2\simulation.py", line 100, in onTrackItemChanged
    item.updateData(msg)
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\abstract.py", line 143, in updateData
    self.updateGraphics()
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\lineitem.py", line 193, in updateGraphics
    self.updateTrain()
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\lineitem.py", line 199, in updateTrain
    self.drawTrain()
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\lineitem.py", line 283, in drawTrain
    self.showTrainLineItem(tlines)
  File "C:\Users\gniew\Desktop\ts2\ts2\scenery\lineitem.py", line 308, in showTrainLineItem
    self._tli[i].hide()

**Comment by npiganeau** [comment]
I don't have enough information in the traceback. Actually, the logs mix logs from the server and the client, and because they are 2 distinct processes, the logs are not necessarily strictly chronological.

Server logs start with INFO (or WARN, etc) such as the first line. When the server crashes, stacktrace is "last on top" because it is a Go stacktrace.

Client logs are all the others. When client crashes, stacktrace is in the opposite order with "last at the bottom" because it is a Python traceback.

Here the first line is ok on server side, then we have a crash on client side, but we don't have the last line with the actual error. And a client crash can be simply because the server crashed before (but may have logged after...).

Just a simple question now: did the screen go black when it crashed ? If yes, this means it is a server crash. Otherwise, when we have a client crash, we may have any kind of other weird behaviour (because python always try to recover from crashes when it can).

**Pull request merged**
