### PR TITLE
Pedro dev

### PR DESCRIPTION
**Pull request by pedromorgan**
Some minor tweaks to startup to load edit

### CODE REVIEW

**Comment by pedromorgan** [comment]
Temp fix forr #68

**Comment by pedromorgan** [comment]
@npiganeau Can u have a quick look and this, to check I'm not "going off the trodden path"..

**Comment by npiganeau** [comment]
@pedromorgan Don't worry, this is the right path ! :-).

I just have two points before merging:

## Time factor

Why do you want to change timeFactor from a simulation option to a setting ?

The original idea behind being a simulation option is that depending on the sim, it is playable at different time factors, e.g.
- Drain sim with time factor less than 5 (or even 10) has no point (the sim is very boring anyway, but you get the point)
- Liverpool street at peak time cannot decently be played at a time factor more than 2.

So having it a sim option enables 2 things:
1. The sim writer can suggest the most appropriate speed to play his sim
2. When the user saves his game (.tsg file) the current time factor is saved and recovers it when he loads the sim again.

## Dirty implementation
You have implemented a self.dirty var to see if the sim has been modified to ask whether we want to save. This is a good idea, but it's only half implemented as I see it (only when routes are added, needs to be also for other modifications). 

If I merge, now I'll disable it temporarily until it is fully implemented so that the user is safe in all cases.

**Comment by pedromorgan** [comment]
Time Factor = Ok, I take the point.. and will think a bit more..

Dirty = Will clean this up soon, but thats why I raise #69 Undo/Redo 

and looking at http://doc.qt.io/qt-5/qundo.html
Although this look rather "complicated" to introduce, and indeed maybe this next version would be easier

**Comment by pedromorgan** [comment]
Can u spin this patch into develop asap.. imho

Amd tidy up interface and things..

I see no issues apart from crash.. 
= BUT u dommit it so when it fails.. its you mistake see @mcgiwer and All

lets merge is fast.. please .. means we all in same HEAD

**Comment by pedromorgan** [comment]
Ok merge this if poss.. as u will as BDFL..

Going into bed soon,
Buys are in there, but lets move on ;-))

ta @npiganeau for a nice  "sunday" = religious IceCream

**Comment by npiganeau** [comment]
I'll look into merging this ASAP, it's just a matter of "I don't have much free time right now"...

**Comment by pedromorgan** [comment]
ta.. 
and advice on how to make this merging easier ?

**Pull request merged**
