### PR TITLE
New path settings and open dialog

### PR DESCRIPTION
**Pull request by pedromorgan**
The idea is to have and integrated dialog to open files, this patch

- adds a debug flag
- moved all `simDir` and `userDir` to `settings`
- integrated open file dialog with downoload, recent and filesystem browser
- mostly working
open_file

### CODE REVIEW

**Comment by pedromorgan** [comment]
Toolbar idea
toolbar

**Comment by pedromorgan** [comment]
dual

**Comment by npiganeau** [comment]
All this seems really cool !

Before I have time for a full review, a few live thoughts:

- I love the toolbar ! Maybe you could separate it into several toolbars so that the user can move them around separately:
    - Actions
    - Time + Speed
    - Zoom
    - Score
- We need a way to open .ts2 files we could have on the hard drive. Maybe an 'import' button from your new open window that would copy the file to the simulation directory ?
- The new "download sims" keeps the file hierarchy of ts2-data so that we can sort the sims. Maybe you could have a tree view inside your new open window to reflect this ?

**Comment by npiganeau** [comment]
I see you started working on the service info view. My idea was to change completely the *info views to make them simply render HTML (through qtextedit) that would be generated directly by the train, service and place instances. 

This will allow these windows to be much cleaner and readable by the user and also remove all the verbose *info models crap.

**Comment by npiganeau** [comment]
And then we could also serve the HTML through the web socket...

**Comment by pedromorgan** [comment]
That sound interesting, but means writing html and css (even js)  ??

Which leads to another question.. How do the resource files work on this project..

I see `resources.qrc` and `resources_rc.py` but am confused on how they work ?? (not a fan of resource files)

**Comment by pedromorgan** [comment]
Maybe we can make the `Service Info View`, `train info view into standalone widgets eg `ServiceInfoWidget`. We can then use these anythere, in dock, in dialog etc etc

**Comment by pedromorgan** [comment]
Actually testing things here, and reviewing a previous project (albeit a long time ago), and thinking about it again... I really dont like the html idea cos its complex, and its how in another lang in another enviroment kinda.. and css nighmares and debugging.......

it might be more effective to create a single "fix for purpose" widget IMHO

**Comment by npiganeau** [comment]
Actually as HTML I was thinking about something very very basic. Just rendering HTML string for display, no CSS (just style=), no js since no interaction. When the info is changed, just reload the whole HTML. See QTextEdit.

My idea was just to have a method in train, service and place such as 
```
def getHtml(self):
    return "<h1>Service code: %s</h1>" % self.serviceCode 
```

Nothing more! Just to display easily those infos in a fixed font white over black for example as in simsig.

**Comment by npiganeau** [comment]
OK I merge this one. There's so much cool stuff in there. Thanks!

**Pull request merged**
