### PR TITLE
Docs Update

### PR DESCRIPTION
**Pull request by pedromorgan**
This is WIP on updating the API docs..

Kinda went down this path as am trying to figure out how things work,, so decided to update docs at the same time..

No code changes, only docs

### CODE REVIEW

**Comment by npiganeau** [comment]
Ok ! Don't hesitate to rewrite the docstring if you think it not clear enough. It's not always easy for me to explain in English the data model.

You might also find functions with doc strings that do not reflect what the method actually do. This can happen on some functions that I have updated and forgot to update the doc. I hope there are not too many.

Finally, when you see import statements in the middle of a function, that is the only workaround I found for circular imports.

**Comment by pedromorgan** [comment]
The doc strings need to "parsable" by sphinx/rst (spits).. so they can work here..
http://docs-ts2.rhcloud.com/dev/how.html

Re, English.... maybe I write docs in my mother tounge .. welsh !!!

Re Imports...
We need to import modules.. and this is easily solvable and a step we should take to future proof..
eg these import need to go imho..
https://github.com/ts2/ts2/blob/develop/ts2/trains/__init__.py

so instead of 
```
from ts2.trains.train import Train
t = Train()
```
its
```
from ts2.trains import train
t = train.Train()
```

I can make these changes if u want...

I also want to rename all the "constants" in __init__..
from ```__FOO__``` to ```FOO``` cos its nicer..

**Comment by npiganeau** [comment]
Imports: if you manage to remove circular imports, please do !

Rename constants: Ok

**Comment by pedromorgan** [comment]
Comments please on the guide... and sections required..

http://docs-ts2.rhcloud.com/dev/quick_guide.html

**Comment by npiganeau** [comment]
Sorry I did not take much time to look at the doc, but it's a great job you're doing here.

### Doc sections
As for docs, that's the main sections I see, generally speaking. The subsections are just here to explain what I imagine inside, but can be different :

1. Install doc
    - Requirements
    - On windows with exe installer and from source
    - On linux from pip and from source

2. User docs for playing
    - Intro to what signalling is (+ newbie links)
    - What is TS2, what is a simulator + what is like in real life and what is different.
    - The mainwindow layout, what is each dock widget for, etc.
    - How to load a sim, what is ts2-data server, how to save a game, ...
    - How to play, create routes, delete routes, ...

3. Sim writers doc
    - What are the basics behind the scene (Track items, routes, train types, services, trains)
    - How to create them inside the editor
    - Tips & tricks to create a sim + potential pitfalls
    - How to create a PR to request adding your sim to ts2-data

4. TS2 extension doc
    - How to create extra signal types for TS2 (for different countries) through .tsl files
    - How to create a new translation for TS2

5. Developer doc
    - Quick code guide
    - API

All this could be in docs-ts2 if you rename it from "developer docs" to "docs".

### Quick code guide
I like the idea. Just a few comments:
- Places should be added as Trackitems, although they are of a special type, they inherit from trackitem and are visible on the scenery.
- SignalItem do not represent a SignalType, they are rather instances of a signal type.
- Probably need 
    - a section for routes, positions
    - a section for train types, trains and services
    - a section for the editor

**Comment by npiganeau** [comment]
And we also need sims doc to describe each sim. 

I think this could be separated and linked with ts2-data server

**Comment by pedromorgan** [comment]
Can we merge this sooner so we dont get outta sync..

Indeed some of this docs stuff, i want to push straight into develop really

**Comment by npiganeau** [comment]
Yes of course you can merge + you can modify docs directly in develop

**Comment by pedromorgan** [comment]
The index is cool.. but not sure where these should go..

What is in my mind is that the dev docs is with the API.. and code..

And the play side, user guide, sim writer is on ts2.github.io .. ie players site..

I need to convert ts2.github.io to jekyll.. or something to make docs easier, particular with international..


Anyway, that is my thoughts.. what u think?

**Comment by pedromorgan** [comment]
@npiganeau said >> "And we also need sims doc to describe each sim."

So how would this work, a simple markdown editor etc.. ?

**Comment by pedromorgan** [comment]
RE comments
@npiganeau said >>
```Places should be added as Trackitems, although they are of a special type, they inherit from trackitem and are visible on the scenery.```

Maybe we need physical items, and logical items.. list. ?
am trying to disinguish between stuf thats real life, and stuff that is not in the scenery..

@npiganeau said >>
```SignalItem do not represent a SignalType, they are rather instances of a signal type.```

Am a bit confused how this works with aspect also..
If you can gimme a couple of lines of how its works would help.. am trying to get to the "logic of how it works".. which is still a bit of a mystery to me .. hence we diving though code..

@npiganeau said >>
```
Probably need
a section for routes, positions
a section for train types, trains and services
a section for the editor
```
Yes please. but I also think we need to make it from the bottom up, or top down to explain..
eg a route is a set of positions

a train is a virtual thing of a train type with its X,y
A Service is a timed based thing that a train needs to run.. etc

I think if u can just knock that stuff of in a few words, then i'll go ans stitch them together..
We can also create diagrams,, like here.. http://docs-ts2.rhcloud.com/api/scenery.html#module-ts2.scenery.pointsitem

We need new developes to be able to get into code qucik style..

Also important is we are limited by sphinx (spits)..
and indeed the pain of a "subClass" ovveride, not including the "parents" docs..
so this means we need the docs in each class, kinda,,,,but we will find workaround I hope...

**Comment by pedromorgan** [comment]
OOPS.. forgot..

Thanks @npiganeau you have put effort into documenting stuff, at least a major bit which is fantastic.. and a huge "pat on the back" from a welshman.. and a free (barrel) beer on me if u ever come to wales for that.. ;-))

But I want to support u, so u can go an knock out code, and not really worry about docs etc etc..

Also I have been in fights with developers about commit patches for docs.. so this is refreshing and cool.. ;-). We want more developers .. and docs is a good starting point imho..

**Pull request merged**
