### PR TITLE
Added coupled points logic

### PR DESCRIPTION
**Pull request by npiganeau**

### CODE REVIEW

**Comment by Sharpe49** [comment]
The positions of the points are wrong. Take a look at this : 
https://github.com/ts2/ts2-data/blob/gretz-coupled-points/France/gretz-armainvilliers.json

Are point positions are normal/reverse instead of left/right ?

**Comment by npiganeau** [comment]
Coupled points are set normal together and reverse together. There is no concept of left-right, but you can set whichever end you want to reverse (it has no impact)

**Comment by Sharpe49** [comment]
Ok, I'll try to invert the positions.

By the way, in the model I talked about during our meeting, we are using left/right for point positions, up/down for derailers, normal/reverse for levers.

**Comment by Sharpe49** [comment]
Ok, it's breaking a lot of my routes...

**Pull request merged**
